### ISSUE TITLE
Work status "Deposited" showing in work view

### ISSUE THREAD

**Issue by julesies** [projecthydra/sufia#3107]
7.3.0rc1

Status (in workflow?) is being displayed on the work view, right under the work title. This is happening when I am logged in and not logged in. 
![screen shot 2017-02-22 at 3 20 49 pm](https://cloud.githubusercontent.com/assets/4356335/23230677/e2520f36-f912-11e6-9960-f0e43543dbe2.png)

I would not expect the deposit status to show for a regular "viewer" of any work view. 

Disclaimer, we are still testing workflows and haven't really got it working, but this happens even to items that are going into the default admin set, which doesn't have an assigned workflow. We upgraded from 7.2.

**Comment by mjgiarlo** [comment]
@julesies Hi, we do have a ticket for making the workflow status more polished and clearer. I'm not sure we have consensus yet on whether this should display or not, or what users this should display to, so for now I am inclined to leave this displaying all the time if that's OK. (And, in the meantime, I'd love for someone to spiffy the design up a bit so it doesn't look... vestigial.) How does that sound? (If cool, feel free to close the issue. If not, it may be good for community discussion.)

**Comment by julesies** [comment]
I can certainly close it. We aren't using 7.3 since we would start fresh on hyrax, just testing. For the future plans, I would worry more about in what context and to who the status shows. I have found mediated deposit is messy and riddled with mistakes and do-overs. So those papers that are in a review process, really shouldn't show to the public at all until it is properly vetted. Perhaps the fact that I'm seeing this when logged out (public view) is related to other bugs or config issues we have going on ❓

**Comment by mjgiarlo** [comment]
@julesies Any works that are under review should **only** be visible to:

* A repository administrator
* A manager for the admin set into which the work was deposited
* A reviewer for the admin set into which the work was deposited
* A user with the `approving` role in the mediated deposit workflow

If they are visible to logged-out users, that is definitely a bug. (And one that I suspect we've already fixed in Hyrax, which could be backported to Sufia.)

**Comment by julesies** [comment]
@mjgiarlo this is still happening, except now only after the review has been approved. This screenshot shows "complete" status. Notice this is the "logged out/public view".
![screen shot 2017-03-13 at 10 09 20 am](https://cloud.githubusercontent.com/assets/4356335/23857904/286d8e70-07d5-11e7-8be9-276db89659e4.png)
